### ISSUE TITLE
A question about the metrics in the experiment under gold evt + gold argument setting 

### ISSUE THREAD

**Issue by Asfalas** [pitrack/arglinking#5]
Hello, I have a question about the setting as the title described. When given the golden argument mentions, the micro-precision\recall\f1 should be the same(Did you use macro- metrics in it?). But in the paper -- 'Multi-Sentence Argument Linking', the experiment under this setting get different values, I don't understand what caused this result. Could you give me a more detailed description? Thank you very much!

**Comment by pitrack** [comment]
Sorry, we don't quite understand your question. Can you ask again: What have you tried? What do you expect, and what do you get instead?

We only reported micro-f1 metrics. Table 2 in the paper shows the difference between gold evt only ("No Given Arguments"), which gets 6.0 F1 and gold evt + gold argument, which should get 68.3 F1. Here, "gold arguments" means given the gold argument spans. Without them, the model effectively needs to perform an additional step of span finding.

**Comment by Asfalas** [comment]
Thank you for your kindly reply. 
Sorry I didn't describ my question well just now.
I mean that when given the golden argument spans and we do classification on them, I think the micro precision and the micro recall should be the same value. Because 
micro-precision=role_correctly_pred_spans/all_pred_spans
  micro-recall=role_correctly_pred_spans/all_gold_spans
here all_pred_spans=all_gold_spans.(if I misunderstand it please point it out. Thank you very much).
But in paper table 2, when given gold evt and gold argument spans in test period, precision is not equal to recall, so I have this question. Thank agian for your kindly reply and your excellent research!

**Comment by pitrack** [comment]
Thanks for the clarification.

Even though we pass in gold spans, the prediction is done independently for each (event, role) pair and the model does not know that each will be used exactly once. For a single event, you can view "all_gold_spans" (for that event) as a "pool" of gold annotated spans that the model picks from for each of its role. So, all_pred_spans != all_gold spans for two reasons:

1. Something from the "pool" isn't picked (none of the roles for the event pick it).
2. Something from the "pool" gets picked twice. This is even more likely since we use greedy decoding (each role for the event can pick multiple argument spans).

**Comment by Asfalas** [comment]
Thanks for your patient explanation!
